INSERT INTO `usuario` (`idusuario`, `apellidos`, `celular`, `correo`, `eliminado`, `fcreate`, `fupdate`, `nombres`, `password_hash`, `vendedor`, `nick`, `ucreate`, `uupdate`, `idarea`) VALUES
  (NULL, 'Admin', '999999999', 'scingerp@gmail.com', b'0', '2021-06-01 00:00:00.000000', NULL, 'Super', '$2a$10$wgEjvYPY9gnw4cN/Jl6wAePzLHA8A/V23DNuRXvEkJkYDvpxNWm2O', b'0', 'Admin', 'Super Admin', NULL, 1),
  (NULL, 'Vendedor', '999999998', 'vendedor@gmail.com', b'0', '2021-06-01 00:00:00.000000', NULL, 'Test', '$2a$10$wgEjvYPY9gnw4cN/Jl6wAePzLHA8A/V23DNuRXvEkJkYDvpxNWm2O', b'1', 'Vendedor A', 'Super Admin', NULL, 2);

INSERT INTO `rol` (`idrol`, `etiqueta`, `nombre`, `ruta`) VALUES
  (NULL, 'Listar usuarios', 'read-usuario', '/pages/usuario/listar'),
  (NULL, 'Crear usuario', 'create-usuario', '/pages/usuario/crear'),
  (NULL, 'Actualizar usuario', 'update-usuario', '/pages/usuario/editar'),
  (NULL, 'Eliminar usuario', 'delete-usuario', '/pages/usuario/eliminar'),

  (NULL, 'Listar clientes', 'read-cliente', '/pages/comercial/cliente/listar'),
  (NULL, 'Crear cliente', 'create-cliente', '/pages/comercial/cliente/crear'),
  (NULL, 'Actualizar cliente', 'update-cliente', '/pages/comercial/cliente/editar'),
  (NULL, 'Eliminar cliente', 'delete-cliente', '/pages/comercial/cliente/eliminar'),

  (NULL, 'Listar documentoclientes', 'read-documentocliente', '/pages/comercial/cliente/documentocliente/listar'),
  (NULL, 'Crear documentocliente', 'create-documentocliente', '/pages/comercial/cliente/documentocliente/crear'),
  (NULL, 'Actualizar documentocliente', 'update-documentocliente', '/pages/comercial/cliente/documentocliente/editar'),
  (NULL, 'Eliminar documentocliente', 'delete-documentocliente', '/pages/comercial/cliente/documentocliente/eliminar'),

  (NULL, 'Listar representantes', 'read-representante', '/pages/comercial/cliente/representante/listar'),
  (NULL, 'Crear representante', 'create-representante', '/pages/comercial/cliente/representante/crear'),
  (NULL, 'Actualizar representante', 'update-representante', '/pages/comercial/cliente/representante/editar'),
  (NULL, 'Eliminar representante', 'delete-representante', '/pages/comercial/cliente/representante/eliminar'),

  (NULL, 'Listar representantetodos', 'read-representantetodo', '/pages/comercial/cliente/representantetodo/listar'),
  (NULL, 'Crear representantetodo', 'create-representantetodo', '/pages/comercial/cliente/representantetodo/crear'),
  (NULL, 'Actualizar representantetodo', 'update-representantetodo', '/pages/comercial/cliente/representantetodo/editar'),
  (NULL, 'Eliminar representantetodo', 'delete-representantetodo', '/pages/comercial/cliente/representantetodo/eliminar'),

  (NULL, 'Listar spcs', 'read-spc', '/pages/comercial/spc/listar'),
  (NULL, 'Crear spc', 'create-spc', '/pages/comercial/spc/crear'),
  (NULL, 'Actualizar spc', 'update-spc', '/pages/comercial/spc/editar'),
  (NULL, 'Eliminar spc', 'delete-spc', '/pages/comercial/spc/eliminar'),

  (NULL, 'Listar documentospcs', 'read-documentospc', '/pages/comercial/spc/documentospc/listar'),
  (NULL, 'Crear documentospc', 'create-documentospc', '/pages/comercial/spc/documentospc/crear'),
  (NULL, 'Actualizar documentospc', 'update-documentospc', '/pages/comercial/spc/documentospc/editar'),
  (NULL, 'Eliminar documentospc', 'delete-documentospc', '/pages/comercial/spc/documentospc/eliminar'),

  (NULL, 'Listar ots', 'read-ot', '/pages/comercial/ot/listar'),
  (NULL, 'Crear ot', 'create-ot', '/pages/comercial/ot/crear'),
  (NULL, 'Actualizar ot', 'update-ot', '/pages/comercial/ot/editar'),
  (NULL, 'Eliminar ot', 'delete-ot', '/pages/comercial/ot/eliminar'),

  (NULL, 'Listar documentoots', 'read-documentoot', '/pages/comercial/ot/documentoot/listar'),
  (NULL, 'Crear documentoot', 'create-documentoot', '/pages/comercial/ot/documentoot/crear'),
  (NULL, 'Actualizar documentoot', 'update-documentoot', '/pages/comercial/ot/documentoot/editar'),
  (NULL, 'Eliminar documentoot', 'delete-documentoot', '/pages/comercial/ot/documentoot/eliminar'),

  (NULL, 'Listar adicionales', 'read-adicional', '/pages/comercial/ot/adicional/listar'),
  (NULL, 'Crear adicional', 'create-adicional', '/pages/comercial/ot/adicional/crear'),
  (NULL, 'Actualizar adicional', 'update-adicional', '/pages/comercial/ot/adicional/editar'),
  (NULL, 'Eliminar adicional', 'delete-adicional', '/pages/comercial/ot/adicional/eliminar'),

  (NULL, 'Listar unidades', 'read-unidad', '/pages/comercial/cliente/unidad/listar'),
  (NULL, 'Crear unidad', 'create-unidad', '/pages/comercial/cliente/unidad/crear'),
  (NULL, 'Actualizar unidad', 'update-unidad', '/pages/comercial/cliente/unidad/editar'),
  (NULL, 'Eliminar unidad', 'delete-unidad', '/pages/comercial/cliente/unidad/eliminar');


INSERT INTO `usuario_rol` (`idusuario`, `idrol`) VALUES
  ('1', '1'),
  ('1', '2'),
  ('1', '3'),
  ('1', '4'),
  ('1', '5'),
  ('1', '6'),
  ('1', '7'),
  ('1', '8'),
  ('1', '9'),
  ('1', '10'),
  ('1', '11'),
  ('1', '12'),
  ('1', '13'),
  ('1', '14'),
  ('1', '15'),
  ('1', '16'),
  ('1', '17'),
  ('1', '18'),
  ('1', '19'),
  ('1', '20'),
  ('1', '21'),
  ('1', '22'),
  ('1', '23'),
  ('1', '24'),
  ('1', '25'),
  ('1', '26'),
  ('1', '27'),
  ('1', '28'),
  ('1', '29'),
  ('1', '30'),
  ('1', '31'),
  ('1', '32'),
  ('1', '33'),
  ('1', '34'),
  ('1', '35'),
  ('1', '36'),
  ('1', '37'),
  ('1', '38'),
  ('1', '39'),
  ('1', '40'),
  ('1', '41'),
  ('1', '42'),
  ('1', '43'),
  ('1', '44');
